version: '3'

services:
  user-service:
    build:
      context: ./user_service
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=user_service.settings
    volumes:
      - ./user_service:/app
    networks:
      - mynetwork

  post-service:
    build:
      context: ./post_service
    ports:
      - "8002:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=post_service.settings
    volumes:
      - ./post_service:/app
    depends_on:
      - user-service
      - rabbitmq
    networks:
      - mynetwork

  notification-service:
    build:
      context: ./notification_service
    ports:
      - "8003:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=notification_service.settings
    volumes:
      - ./notification_service:/app
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  celery_notification_worker:
    build:
      context: ./notification_service
    container_name: celery_notification_worker
    command: celery -A notification_service worker --loglevel=info
    depends_on:
      - notification-service
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=notification_service.settings
    networks:
      - mynetwork

  celery_post_worker:
    build:
      context: ./post_service
    container_name: celery_post_worker
    command: celery -A post_service worker --loglevel=info
    depends_on:
      - post-service
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=post_service.settings
    networks:
      - mynetwork

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge