version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - mynetwork

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: -Xms32M -Xmx64M
    depends_on:
      - zookeeper
      - kafka
    networks:
      - mynetwork

  user-service:
    build:
      context: ./user_service
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=user_service.settings
    volumes:
      - ./user_service:/app
    networks:
      - mynetwork

  post-service:
    build:
      context: ./post_service
    ports:
      - "8002:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=post_service.settings
    volumes:
      - ./post_service:/app
    depends_on:
      - user-service
      - kafka
    networks:
      - mynetwork

  notification-service:
    build:
      context: ./notification_service
    ports:
      - "8003:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=notification_service.settings
    volumes:
      - ./notification_service:/app
    depends_on:
      - kafka
    networks:
      - mynetwork

  api-gateway:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - post-service
      - notification-service
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
